domain_path: E:\test-xilinx-bare-metal-sw-only\sw\artyz7_platform\export\artyz7_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: E:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
